#spring.datasource.url=jdbc:postgresql://localhost:5432/db_project_2
#spring.datasource.username=postgres
#spring.datasource.password=admin
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#
#
#logging.level.org.springframework.security=DEBUG
#
#server.port=8081
#
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.main.banner-mode=off

server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springBoot
    username: postgres
    password: 
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally-quoted-identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: never   # at first put it always then put it never
      continue-on-error: false